### ISSUE TITLE
Checksum is incorrectly calculated.

### ISSUE THREAD

**Issue by mungewell** [twam/EDID#1]
The checksum is incorrect calculated, resulting in an invalid EDID. It also does not account for the fact that there may extension blocks, so it needs to be written at a fixed location.

Patch below.
[checksum.patch.txt](https://github.com/twam/EDID/files/881142/checksum.patch.txt)

**Comment by twam** [comment]
Thanks for the patch!

**Comment by twam** [comment]
Hmm... Commited this blindly, however the unit tests now fail. Had a deeper look and agree on the change of the fixed location, however not on the correction on the checksum calculation. You're missing byte 127 and why the change from 256 to 255?

**Comment by mungewell** [comment]
Checksum is a particularly stupid schema. All the bytes in the block (0 through 127, including checksum byte) add to zero... so "all except checksum" is computed from bytes 0 through 126.

"% 256" will give 0..255, thus checksum calculation needs to be "255 - (sum % 256)" otherwise it is impossible to get an output value of 0. Maybe you don't need the 2nd "% 256" at all.

Noticed and validated by using another EDID reader "edid-decode" on the output. Maybe the unit test is broken?
Simon

**Comment by twam** [comment]
The original code says `for i in self[0:127]`. As the second index is not included, it uses bytes 0 through 126. Your change would miss byte 126.

If the sum is 0, the checksum needs to be 0 as well, but if you calculate 255 - (0 % 256) you get 255. However with `(256 - (sum % 256)) % 256` you get an output of 0.

**Comment by mungewell** [comment]
Did you try using your code with edid-decode? (sudo apt-get install edid-decode).

Sample script attached for what I was doing.  If it now works, great...
[fix-serial.py.txt](https://github.com/twam/EDID/files/907849/fix-serial.py.txt)

$ python fix-serial.py example.bin 1234 > result.bin

Simon.
